#------------------#
# General Settings #
#------------------#
rankpublic: true
trackRanks: false
defaultrankallworlds: false
onlyoneclass: true
signcheck: false
signchoose: '[choose]'
signrankup: '[rankup]'
signrankdown: '[rankdown]'
cooldown: 0
debug: false
checkprices: true
checkitems: true
checkexp: true

#----------------#
# Color Settings #
#----------------#
playercolor: '&e'
worldcolor: '&6'

#---------------------#
# Money Cost Settings #
#---------------------#
prices:
    I: '10.00'
    II: '50.00'
    III: '100.00'

#--------------------#
# Item Cost Settings #
#--------------------#
items:
    I:
    - 'REDSTONE:2'
    - 'COAL:2'
    II:
    - 'GOLD_INGOT:2'
    - 'IRON_INGOT:3'
    III:
    - 'DIAMOND:5'
    - 'LAPIS_BLOCK:5'

#-------------------#
# EXP Cost Settings #
#-------------------#
exp:
    I: '10'
    II: '50'
    III: '100'

#---------#
# Classes #
#---------#

classes:
    Fighter:
        Warrior: 'Warrior I:&7'
        SWarrior: 'Warrior II:&7'
        MWarrior: 'Warrior III:&8'
    Business:
        Trader: 'Trader I:&a'
        STrader: 'Trader II:&a'
        MTrader: 'Trader III:&2'

#---------#
# Players #
#---------#

players:
    Notch:
        Fighter: Warrior

#------------------#
# Config debugging #
#------------------#
cversion: '0200'
